# Generated by Django 5.0.4 on 2024-05-05 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quize',
            fields=[
                ('Quize_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quize_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(default='Uncategorized', max_length=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.course')),
            ],
        ),
    ]
