# Generated by Django 5.0.4 on 2024-05-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quize_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='course_name',
            field=models.ForeignKey(default='Uncategorized', max_length=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.course'),
        ),
    ]
