# Generated by Django 5.0.5 on 2024-05-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quize',
            name='course_name',
        ),
        migrations.AddField(
            model_name='quize',
            name='course_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='Quizzes', to='api.course'),
        ),
    ]
