# Generated by Django 5.0.4 on 2024-05-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_quize_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_of_quizzes',
        ),
    ]
